crawling/crawling/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from naver.views import ArticleList, ArticleDetail

urlpatterns = [
    url(r'^naver/', include([
        url(r'^$', ArticleList.as_view(), name='list'),
        url(r'^(?P<pk>[0-9]+)/$', ArticleDetail.as_view(), name='detail'),
    ], namespace='naver')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    # Serve static and media files from development server
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crawling/naver/models.py
from django.db import models


class Article(models.Model):

    title = models.CharField(max_length=255)
    time = models.DateTimeField(blank=True, null=True)
    body = models.TextField()
    url = models.URLField()

    author = models.ManyToManyField('Author', related_name='articles', blank=True, null=True)
    publisher = models.ForeignKey('Publisher', blank=True, null=True, on_delete=models.SET_NULL, related_name='articles')

    def __str__(self):
        return self.title


class Publisher(models.Model):

    name = models.CharField(max_length=255)
    logo = models.ImageField(upload_to='publishers/', blank=True, null=True)

    def __str__(self):
        return self.name


class Author(models.Model):

    name = models.CharField(max_length=255)
    publisher = models.ForeignKey(Publisher, blank=True, null=True, on_delete=models.SET_NULL, related_name='authors')

    def __str__(self):
        return self.name

crawling/naver/views.py
from django.shortcuts import render

import requests
from bs4 import BeautifulSoup
import re

def remove_html_tags(data):
    p = re.compile(r'<.*?>')
    return p.sub('\n',data)

def get_single_article(item_url):
    source_code = requests.get(item_url)
    plain_text=source_code.text
    soup = BeautifulSoup(plain_text, 'html.parser')
    title = soup.select('#articleTitle')[0].get_text()
    url=item_url
    publisher=soup.select('.press_logo > a > img')[0].attrs['title']

    #title, url, author, publisher, date
    for content in soup.select('#articleBodyContents'):
        try:
            content_list.append(content)
        except NameError:
            content_list = [content]

    article_data = {
        'title': title,
        'url': url,
        'publisher': publisher,
        'content_list': content_list,
    }

    return article_data

get_single_article('http://news.naver.com/main/read.nhn?mode=LSD&mid=shm&sid1=101&oid=052&aid=0000791309')

crawling/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/crawling.css">
    {% block extra_css %}{% endblock %}
  </head>
  <body class="{% block body_class %}{% endblock %}">
    <main>
      {% block header %}{% endblock %}
      {% block content %}{% endblock %}
      {% block footer %}{% endblock %}
    </main>
    {% block extra_js %}{% endblock %}
  </body>
</html>

crawling/templates/naver/article_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="article-detail">
  <div class="container">
    <h1 class="article-title">{{ article.title }}</h1>
    <div class="article-publisher">{{ article.publisher }}</div>
    <div class="article-author">{{ article.author }}</div>
    <div class="article-body">{{ article.body|safe }}</div>
  </div>
</div>
{% endblock %}

crawling/templates/naver/article_list.html
{% extends 'base.html' %}

{% block content %}
<div class="article-list">
  <div class="container">
    <h1>네이버 기사 목록</h1>
    <ul class="article_list">
      {% for article in articles %}
      <li>
        <a href="{% url 'naver:detail' article.id %}">{{ article.title }}</li></a>
        <span>{{ article.publisher }}</span>
        <span>{{ article.time }}</span>
      {% endfor %}
    </ul>
  </div>
</div>
{% endblock %}